In [1]:
import numpy as np

print(np.__version__)
print(np.__config__)

1.26.1
<module 'numpy.__config__' from 'C:\\Users\\ADMIN\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\__config__.py'>


In [ ]:
import numpy as np


arr = np.arange(10)

arr_odd = arr[arr % 2 != 0]

arr_even = arr[arr % 2 == 0]

arr_update_1 = arr.copy()

arr_update_1[arr_update_1 % 2 != 0] = 100

print(arr_update_1)

print("Cac phan tu trong arr:", arr)

print("Kieu du lieu cua arr:", arr.dtype)


print("Kich thuoc cua arr:", arr.shape)

print("Arr_odd:", arr_odd)

print("Arr_even:", arr_even)

In [2]:
import numpy as np

arr_a = np.array([1,2,3,2,3,4,3,4,5,6])

arr_b = np.array([17,2,10,2,71,27,9,27,9,55])

arr_e = np.array([5, 6, 0, 9, 10, 3, 24, 17, 6, 36, 86])

arr_c = arr_a[arr_a == arr_b]

arr_d = arr_a[arr_a != arr_b]

arr_f = arr_e[arr_e <= 10]

arr_f = arr_f[arr_f >= 5]

print(arr_c)

print(arr_d)

print(arr_f)

[2 2]
[1 3 3 4 3 4 5 6]
[ 5  6  9 10  6]


In [3]:
import numpy as np

arr_zeros = np.zeros(10)

arr_zeros = np.insert(arr_zeros, 5, 1)

arr_zeros = np.delete(arr_zeros, 10)

arr_h = np.linspace(10, 24, 14, dtype = int)

arr_h_reversed_sort = np.sort(arr_h)[::-1]

arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])

arr_1 = arr_k[arr_k != 0]

arr_1_append = np.append(arr_1, (10, 20))

arr_1_append_insert = np.insert(arr_1_append, 5, 100)

arr_1_append_insert_delete = np.delete(arr_1_append_insert, (0,1,2))

print(arr_zeros)

print(arr_h)

print(arr_h_reversed_sort)

print(arr_1)

print(arr_1_append)

print(arr_1_append_insert)

print(arr_1_append_insert_delete)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 24]
[24 22 21 20 19 18 17 16 15 14 13 12 11 10]
[1 2 8 2 1 3 5]
[ 1  2  8  2  1  3  5 10 20]
[  1   2   8   2   1 100   3   5  10  20]
[  2   1 100   3   5  10  20]
