In [6]:
import numpy as np
my_list = [1,2,3,4,5]
arr_2 = np.array(my_list, dtype=float)
print(arr_2)

[1. 2. 3. 4. 5.]


In [5]:
import numpy as np
np.zeros(5,dtype=int)
arr_3 = np.arange(0,1,0.1,dtype=float)
print(arr_3)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [2]:
import numpy as np
np.ones((3,3), dtype=float)
np.full((5,5),100,dtype=float)

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [8]:
import numpy as np
arr_1 = np.linspace(0,10,5)
print(arr_1)

arr_2 = np.linspace(0,1,10,endpoint=False)
print(arr_2)

arr_3, step = np.linspace(1,10,100,retstep=True)
print(arr_3)
print("Step size:", step)

[ 0.   2.5  5.   7.5 10. ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8

In [11]:
import numpy as np
arr_7 = np.random.randint(0,10,(3,3))
print(arr_7)

np.eye(3,3)

np.empty(5)

[[4 3 4]
 [3 0 5]
 [2 9 8]]


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

print("so chieu cua mang:", arr.ndim)
print("kich thuoc cua mang:", arr.shape)
print("tong so phan tu cua mang:", arr.shape)
print("kieu du lieu cua cac phan tu:", arr.dtype)
print("kich thuoc(byte) cua moi phan tu:", arr.itemsize)
print("tong kich thuoc(byte)cua mang:", arr.nbytes)

so chieu cua mang: 2
kich thuoc cua mang: (2, 3)
tong so phan tu cua mang: (2, 3)
kieu du lieu cua cac phan tu: int32
kich thuoc(byte) cua moi phan tu: 4
tong kich thuoc(byte)cua mang: 24


In [16]:
import numpy as np
arr_a = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
np.sum(arr_a)
np.sum(arr_a, axis=0)
np.sum(arr_a, axis=1)

array([10, 26, 42])

In [ ]:
import numpy as np


In [5]:
import numpy as np
my_list = [1,2,3,4,5]
arr_1 = np.array(my_list)
print(arr_1)

[1 2 3 4 5]
